export default function StudyPlan() {
  const plan = [
    { day: "Day 1 (Today)", focus: "Geometry Fundamentals", duration: "45 mins" },
    { day: "Day 2", focus: "Algebra Practice", duration: "30 mins" },
    { day: "Day 3", focus: "Geometry Advanced & Quiz", duration: "60 mins" },
    { day: "Day 4", focus: "Calculus Review", duration: "30 mins" }
  ];

  return (
    <div className="animate-fade-in" style={{ maxWidth: '800px', margin: '0 auto' }}>
      <h2>Smart Study Plan</h2>
      <p style={{ color: 'var(--text-muted)', marginBottom: '2rem' }}>
        Generated by StudySmart AI using spaced repetition for your weak topics.
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {plan.map((item, idx) => (
          <div key={idx} className="glass-panel" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem' }}>
            <div>
              <div style={{ color: 'var(--primary)', fontWeight: '600', marginBottom: '0.5rem' }}>{item.day}</div>
              <div style={{ fontSize: '1.1rem' }}>{item.focus}</div>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.1)', padding: '0.5rem 1rem', borderRadius: '20px', fontSize: '0.9rem' }}>
              ⏱ {item.duration}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
